[[plugins]]
repo = 'Shougo/deoppet.nvim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tabline#enabled = 1
    nmap <C-p> <Plug>AirlineSelectPrevTab
    nmap <C-n> <Plug>AirlineSelectNextTab
    let g:airline_theme = 'violet'
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'
hook_add = '''
let g:cursorhold_updatetime = 100
'''

[[plugins]]
repo = 'preservim/nerdtree'
