BASE_PATH = $(HOME)/ghq/.dotfiles

include $(BASE_PATH)/Makefile.1-brew
include $(BASE_PATH)/Makefile.2-init
include $(BASE_PATH)/Makefile.3-zsh-setup
include $(BASE_PATH)/Makefile.4-formulae-setup
include $(BASE_PATH)/Makefile.6-asdf-setup
include $(BASE_PATH)/Makefile.7-neovim-setup
include $(BASE_PATH)/Makefile.8-appstore-setup
