# Makes yarn more easily accessible.
alias yrd='yarn run dev'
alias yrf='yarn run fix'
alias yrw='yarn run watch'
alias yrs='yarn run start'
alias yi='yarn install'
alias yrb='yarn run build'
alias yrg='yarn run generate'
alias yrf='yarn run fix'
alias yrsb='yarn storybook'
