[v1]
"cargo-update 11.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"exa 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"zoxide 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
